# Site settings
title: Blogs | Ashish Jaiswal
description: "A place to show off my thoughts."
url: "http://www.jashish.com.np/blogs"
author:
  name: "Ashish Jaiswal"
  email: "ashiz2013@gmail.com"
  url: "http://jashish.com.np"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
